AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/MethodLength:
  Max: 15
